Refactoring import
votedotorg/votedotorg-state-site-tracking pull request #17
Opened 2020-09-25 20:19 UTC by adeolaawoyemi

2020-09-25 20:25 UTC, BruceBGordon requested changes

2020-09-25 20:25 UTC, BruceBGordon commented on README.md
> +We use the dotenv package to to manege environment variables needed for things
man*a*ge

2020-09-25 20:25 UTC, BruceBGordon commented on README.md
> +To setup conneting to the database, copy the file `.env.template` to `.env`
conne*c*ting

2020-09-25 20:25 UTC, BruceBGordon commented on README.md
> +to connect to the datase get the right connection info.
data*ba*se  ... *to* get the right connection

2020-09-29 06:03 UTC, yahoo-che approved these changes

2020-09-29 13:45 UTC, adeolaawoyemi commented
@BruceBGordon please approve this PR as well since you requested changes to the README that I've done.

2020-09-29 15:02 UTC, BruceBGordon approved these changes

2020-09-29 15:02 UTC, merged